library(data.table)

#Set working directory where model output is stored
##Use the model code in "/2 - Tests/abm_12-4-2021_master.R" to generate the model output -- this code collects additional results used to unit test the model output
setwd("C:/Users/johnc/Dropbox (Harvard University)/Documents/Research/COVID-19/BackToSchool2/2 - Tests/Test Output")

#Bind model output into single data table
filelist <- list.files(pattern = paste("elem_results_", 1, "_.*RData", sep = ""))
output <- rbindlist(lapply(1:length(filelist), function(a){load(filelist[a]); output = output; return(output)}))

output <- data.table(output)

#Create summary measures of model output, grouped by model input parameters
output <- output[,.(inf_ct_sympK_A_home.sum = sum(inf_ct_sympK_A_home, na.rm = TRUE), inf_ct_asympK_A_home.sum = sum(inf_ct_asympK_A_home, na.rm = TRUE), inf_ct_sympA_A_home.sum = sum(inf_ct_sympA_A_home, na.rm = TRUE), inf_ct_asympA_A_home.sum = sum(inf_ct_asympA_A_home, na.rm = TRUE), inf_ct_sympK_K_home.sum = sum(inf_ct_sympK_K_home, na.rm = TRUE), inf_ct_asympK_K_home.sum = sum(inf_ct_asympK_K_home, na.rm = TRUE), inf_ct_sympA_K_home.sum = sum(inf_ct_sympA_K_home, na.rm = TRUE), inf_ct_asympA_K_home.sum = sum(inf_ct_asympA_K_home, na.rm = TRUE),
                    inf_ct_sympK_A_class.sum = sum(inf_ct_sympK_A_class, na.rm = TRUE), inf_ct_asympK_A_class.sum = sum(inf_ct_asympK_A_class, na.rm = TRUE), inf_ct_sympA_A_class.sum = sum(inf_ct_sympA_A_class, na.rm = TRUE), inf_ct_asympA_A_class.sum = sum(inf_ct_asympA_A_class, na.rm = TRUE), inf_ct_sympK_K_class.sum = sum(inf_ct_sympK_K_class, na.rm = TRUE), inf_ct_asympK_K_class.sum = sum(inf_ct_asympK_K_class, na.rm = TRUE), inf_ct_sympA_K_class.sum = sum(inf_ct_sympA_K_class, na.rm = TRUE), inf_ct_asympA_K_class.sum = sum(inf_ct_asympA_K_class, na.rm = TRUE),
                    inf_ct_sympK_A_specials.sum = sum(inf_ct_sympK_A_specials, na.rm = TRUE), inf_ct_asympK_A_specials.sum = sum(inf_ct_asympK_A_specials, na.rm = TRUE), inf_ct_sympA_A_specials.sum = sum(inf_ct_sympA_A_specials, na.rm = TRUE), inf_ct_asympA_A_specials.sum = sum(inf_ct_asympA_A_specials, na.rm = TRUE), inf_ct_sympK_K_specials.sum = sum(inf_ct_sympK_K_specials, na.rm = TRUE), inf_ct_asympK_K_specials.sum = sum(inf_ct_asympK_K_specials, na.rm = TRUE), inf_ct_sympA_K_specials.sum = sum(inf_ct_sympA_K_specials, na.rm = TRUE), inf_ct_asympA_K_specials.sum = sum(inf_ct_asympA_K_specials, na.rm = TRUE),
                    inf_ct_sympK_A_rand.sum = sum(inf_ct_sympK_A_rand, na.rm = TRUE), inf_ct_asympK_A_rand.sum = sum(inf_ct_asympK_A_rand, na.rm = TRUE), inf_ct_sympA_A_rand.sum = sum(inf_ct_sympA_A_rand, na.rm = TRUE), inf_ct_asympA_A_rand.sum = sum(inf_ct_asympA_A_rand, na.rm = TRUE), inf_ct_sympK_K_rand.sum = sum(inf_ct_sympK_K_rand, na.rm = TRUE), inf_ct_asympK_K_rand.sum = sum(inf_ct_asympK_K_rand, na.rm = TRUE), inf_ct_sympA_K_rand.sum = sum(inf_ct_sympA_K_rand, na.rm = TRUE), inf_ct_asympA_K_rand.sum = sum(inf_ct_asympA_K_rand, na.rm = TRUE),
                    inf_ct_sympK_A_care.sum = sum(inf_ct_sympK_A_care, na.rm = TRUE), inf_ct_asympK_A_care.sum = sum(inf_ct_asympK_A_care, na.rm = TRUE), inf_ct_sympA_A_care.sum = sum(inf_ct_sympA_A_care, na.rm = TRUE), inf_ct_asympA_A_care.sum = sum(inf_ct_asympA_A_care, na.rm = TRUE), inf_ct_sympK_K_care.sum = sum(inf_ct_sympK_K_care, na.rm = TRUE), inf_ct_asympK_K_care.sum = sum(inf_ct_asympK_K_care, na.rm = TRUE), inf_ct_sympA_K_care.sum = sum(inf_ct_sympA_K_care, na.rm = TRUE), inf_ct_asympA_K_care.sum = sum(inf_ct_asympA_K_care, na.rm = TRUE),
                    inf_ct_sympA_A_staff.sum = sum(inf_ct_sympA_A_staff, na.rm = TRUE), inf_ct_asympA_A_staff.sum = sum(inf_ct_asympA_A_staff, na.rm = TRUE),
                    
                    risk_ct_sympK_A_home.sum = sum(risk_ct_sympK_A_home, na.rm = TRUE), risk_ct_asympK_A_home.sum = sum(risk_ct_asympK_A_home, na.rm = TRUE), risk_ct_sympA_A_home.sum = sum(risk_ct_sympA_A_home, na.rm = TRUE), risk_ct_asympA_A_home.sum = sum(risk_ct_asympA_A_home, na.rm = TRUE), risk_ct_sympK_K_home.sum = sum(risk_ct_sympK_K_home, na.rm = TRUE), risk_ct_asympK_K_home.sum = sum(risk_ct_asympK_K_home, na.rm = TRUE), risk_ct_sympA_K_home.sum = sum(risk_ct_sympA_K_home, na.rm = TRUE), risk_ct_asympA_K_home.sum = sum(risk_ct_asympA_K_home, na.rm = TRUE),
                    risk_ct_sympK_A_class.sum = sum(risk_ct_sympK_A_class, na.rm = TRUE), risk_ct_asympK_A_class.sum = sum(risk_ct_asympK_A_class, na.rm = TRUE), risk_ct_sympA_A_class.sum = sum(risk_ct_sympA_A_class, na.rm = TRUE), risk_ct_asympA_A_class.sum = sum(risk_ct_asympA_A_class, na.rm = TRUE), risk_ct_sympK_K_class.sum = sum(risk_ct_sympK_K_class, na.rm = TRUE), risk_ct_asympK_K_class.sum = sum(risk_ct_asympK_K_class, na.rm = TRUE), risk_ct_sympA_K_class.sum = sum(risk_ct_sympA_K_class, na.rm = TRUE), risk_ct_asympA_K_class.sum = sum(risk_ct_asympA_K_class, na.rm = TRUE),
                    risk_ct_sympK_A_specials.sum = sum(risk_ct_sympK_A_specials, na.rm = TRUE), risk_ct_asympK_A_specials.sum = sum(risk_ct_asympK_A_specials, na.rm = TRUE), risk_ct_sympA_A_specials.sum = sum(risk_ct_sympA_A_specials, na.rm = TRUE), risk_ct_asympA_A_specials.sum = sum(risk_ct_asympA_A_specials, na.rm = TRUE), risk_ct_sympK_K_specials.sum = sum(risk_ct_sympK_K_specials, na.rm = TRUE), risk_ct_asympK_K_specials.sum = sum(risk_ct_asympK_K_specials, na.rm = TRUE), risk_ct_sympA_K_specials.sum = sum(risk_ct_sympA_K_specials, na.rm = TRUE), risk_ct_asympA_K_specials.sum = sum(risk_ct_asympA_K_specials, na.rm = TRUE),
                    risk_ct_sympK_A_rand.sum = sum(risk_ct_sympK_A_rand, na.rm = TRUE), risk_ct_asympK_A_rand.sum = sum(risk_ct_asympK_A_rand, na.rm = TRUE), risk_ct_sympA_A_rand.sum = sum(risk_ct_sympA_A_rand, na.rm = TRUE), risk_ct_asympA_A_rand.sum = sum(risk_ct_asympA_A_rand, na.rm = TRUE), risk_ct_sympK_K_rand.sum = sum(risk_ct_sympK_K_rand, na.rm = TRUE), risk_ct_asympK_K_rand.sum = sum(risk_ct_asympK_K_rand, na.rm = TRUE), risk_ct_sympA_K_rand.sum = sum(risk_ct_sympA_K_rand, na.rm = TRUE), risk_ct_asympA_K_rand.sum = sum(risk_ct_asympA_K_rand, na.rm = TRUE),
                    risk_ct_sympK_A_care.sum = sum(risk_ct_sympK_A_care, na.rm = TRUE), risk_ct_asympK_A_care.sum = sum(risk_ct_asympK_A_care, na.rm = TRUE), risk_ct_sympA_A_care.sum = sum(risk_ct_sympA_A_care, na.rm = TRUE), risk_ct_asympA_A_care.sum = sum(risk_ct_asympA_A_care, na.rm = TRUE), risk_ct_sympK_K_care.sum = sum(risk_ct_sympK_K_care, na.rm = TRUE), risk_ct_asympK_K_care.sum = sum(risk_ct_asympK_K_care, na.rm = TRUE), risk_ct_sympA_K_care.sum = sum(risk_ct_sympA_K_care, na.rm = TRUE), risk_ct_asympA_K_care.sum = sum(risk_ct_asympA_K_care, na.rm = TRUE),
                    risk_ct_sympA_A_staff.sum = sum(risk_ct_sympA_A_staff, na.rm = TRUE), risk_ct_asympA_A_staff.sum = sum(risk_ct_asympA_A_staff, na.rm = TRUE),
                    
                    length.infectious_obs.mean = mean(length.infectious_obs, na.rm = TRUE), length.infectious_sd.mean = mean(length.infectious_sd, na.rm = TRUE), length.infectious.school.symp.present_obs.mean = mean(length.infectious.school.symp.present_obs, na.rm = TRUE), length.infectious.school.asymp.present_obs.mean = mean(length.infectious.school.asymp.present_obs, na.rm = TRUE), length.infectious.school.symp.family_obs.mean = mean(length.infectious.school.symp.family_obs, na.rm = TRUE), length.infectious.school.asymp.family_obs.mean = mean(length.infectious.school.asymp.family_obs, na.rm = TRUE),
                    n_students_obs.mean = mean(n_students_obs, na.rm = TRUE), n_teachers_obs.mean = mean(n_teachers_obs, na.rm = TRUE), n_staff_obs.mean  = mean(n_staff_obs, na.rm = TRUE),
                    p_asymp_adult_obs.mean = mean(p_asymp_adult_obs, na.rm = TRUE), p_asymp_child_obs.mean = mean(p_asymp_child_obs, na.rm = TRUE), p_subclin_adult_obs.mean = mean(p_subclin_adult_obs, na.rm = TRUE), p_subclin_child_obs.mean = mean(p_subclin_child_obs, na.rm = TRUE),
                    length.incubation_obs.mean = mean(length.incubation_obs, na.rm = TRUE), length.symp.gap_obs.mean = mean(length.symp.gap_obs, na.rm = TRUE),
                    child.vax.rate_obs.mean = mean(child.vax.rate_obs, na.rm = TRUE), teacher.vax.rate_obs.mean = mean(teacher.vax.rate_obs, na.rm = TRUE), family.vax.rate_obs.mean = mean(family.vax.rate_obs, na.rm = TRUE), vax.eff_obs.mean = mean(vax.eff_obs, na.rm = TRUE),
                    child.prob_obs.mean = mean(child.prob_obs, na.rm = TRUE), adult.prob_obs.mean = mean(adult.prob_obs, na.rm = TRUE),
                    
                    rapid_test_sens.obs = sum(rapid_tp_count)/(sum(rapid_tp_count)+sum(rapid_fn_count)), pcr_test_sens.obs = sum(pcr_tp_count)/(sum(pcr_tp_count)+sum(pcr_fn_count)), test_regular_frac.obs = sum(test_regular)/sum(test_regular_eligible), test_quarantine_frac.obs = sum(test_qs)/sum(test_q_eligible),
                    
                    group = paste(mitigation, prob, p_asymp_adult, p_asymp_child, p_subclin_adult, p_subclin_child, mult_asymp_child, mult_asymp, days_inf, rel_trans_child_symp_HH, vax_eff, attack.df, variant.attack, child.vax, teacher_susp, child_susp, child_trans, family_susp, adult_prob, child_prob, test, test_frac, isolate, notify, rel_trans_HH, rel_trans_child_symp_HH, rel_trans, rel_trans_adult, rel_trans_CC, high_school, n_class, type, test_sens, rapid_test_sens, test_frac, test_quarantine)),
                    
                    by = .(mitigation, prob, p_asymp_adult, p_asymp_child, p_subclin_adult, p_subclin_child, mult_asymp_child, mult_asymp, days_inf, rel_trans_child_symp_HH, vax_eff, attack.df, variant.attack, child.vax, teacher_susp, child_susp, child_trans, family_susp, adult_prob, child_prob, test, test_frac, isolate, notify, rel_trans_HH, rel_trans_child_symp_HH, rel_trans, rel_trans_adult, rel_trans_CC, high_school, n_class, type, test_sens, rapid_test_sens, test_frac, test_quarantine)]

#Create table to compare observed SAR with predicted SAR
##NB: This does not really work with testing yet, since it is difficult to determine a closed-form formula for the predicted SAR
sar.compare <- expand.grid(location = c("home", "class", "specials", "random", "staff.random", "care"), adult.source = c(T, F), adult.susp = c(T,F), symptomatic = c(T,F), group = output$group) %>% left_join(output, by = "group") %>%
  mutate(expected.sar = attack.df*
           ifelse(location == "home", rel_trans_HH*ifelse(!adult.source & symptomatic, rel_trans_child_symp_HH, 1), 1)*
           ifelse(location == "specials", ifelse(adult.source | adult.susp, rel_trans, NA), 1)*
           ifelse(location == "random", rel_trans, 1)*
           ifelse(location == "staff.random", ifelse(adult.source & adult.susp, rel_trans*rel_trans_adult, NA), 1)*
           ifelse(location == "care", rel_trans_CC, 1)*
           ifelse(!adult.source, child_trans,1)*
           ifelse(adult.source & !symptomatic, mult_asymp, 1)*
           ifelse(!adult.source & !symptomatic, mult_asymp_child, 1)*
           ifelse(!adult.susp, child_susp, 1)*
           ifelse(adult.source & adult.susp & (location %in% c("class")), NA, 1)) %>%
  relocate(expected.sar) %>%
  mutate(observed.sar = ifelse(location == "home",
                               ifelse(adult.source,
                                      ifelse(adult.susp,
                                             ifelse(symptomatic,
                                                    inf_ct_sympA_A_home.sum/risk_ct_sympA_A_home.sum,
                                                    inf_ct_asympA_A_home.sum/risk_ct_asympA_A_home.sum),
                                             ifelse(symptomatic,
                                                    inf_ct_sympA_K_home.sum/risk_ct_sympA_K_home.sum,
                                                    inf_ct_asympA_K_home.sum/risk_ct_asympA_K_home.sum)),
                                      ifelse(adult.susp,
                                             ifelse(symptomatic,
                                                    inf_ct_sympK_A_home.sum/risk_ct_sympK_A_home.sum,
                                                    inf_ct_asympK_A_home.sum/risk_ct_asympK_A_home.sum),
                                             ifelse(symptomatic,
                                                    inf_ct_sympK_K_home.sum/risk_ct_sympK_K_home.sum,
                                                    inf_ct_asympK_K_home.sum/risk_ct_asympK_K_home.sum))),
                               ifelse(location == "class",
                                      ifelse(adult.source,
                                             ifelse(adult.susp,
                                                    ifelse(symptomatic,
                                                           inf_ct_sympA_A_class.sum/risk_ct_sympA_A_class.sum,
                                                           inf_ct_asympA_A_class.sum/risk_ct_asympA_A_class.sum),
                                                    ifelse(symptomatic,
                                                           inf_ct_sympA_K_class.sum/risk_ct_sympA_K_class.sum,
                                                           inf_ct_asympA_K_class.sum/risk_ct_asympA_K_class.sum)),
                                             ifelse(adult.susp,
                                                    ifelse(symptomatic,
                                                           inf_ct_sympK_A_class.sum/risk_ct_sympK_A_class.sum,
                                                           inf_ct_asympK_A_class.sum/risk_ct_asympK_A_class.sum),
                                                    ifelse(symptomatic,
                                                           inf_ct_sympK_K_class.sum/risk_ct_sympK_K_class.sum,
                                                           inf_ct_asympK_K_class.sum/risk_ct_asympK_K_class.sum))),
                                      ifelse(location == "specials",
                                             ifelse(adult.source,
                                                    ifelse(adult.susp,
                                                           ifelse(symptomatic,
                                                                  inf_ct_sympA_A_specials.sum/risk_ct_sympA_A_specials.sum,
                                                                  inf_ct_asympA_A_specials.sum/risk_ct_asympA_A_specials.sum),
                                                           ifelse(symptomatic,
                                                                  inf_ct_sympA_K_specials.sum/risk_ct_sympA_K_specials.sum,
                                                                  inf_ct_asympA_K_specials.sum/risk_ct_asympA_K_specials.sum)),
                                                    ifelse(adult.susp,
                                                           ifelse(symptomatic,
                                                                  inf_ct_sympK_A_specials.sum/risk_ct_sympK_A_specials.sum,
                                                                  inf_ct_asympK_A_specials.sum/risk_ct_asympK_A_specials.sum),
                                                           ifelse(symptomatic,
                                                                  inf_ct_sympK_K_specials.sum/risk_ct_sympK_K_specials.sum,
                                                                  inf_ct_asympK_K_specials.sum/risk_ct_asympK_K_specials.sum))),
                                             ifelse(location == "random",
                                                    ifelse(adult.source,
                                                           ifelse(adult.susp,
                                                                  ifelse(symptomatic,
                                                                         inf_ct_sympA_A_rand.sum/risk_ct_sympA_A_rand.sum,
                                                                         inf_ct_asympA_A_rand.sum/risk_ct_asympA_A_rand.sum),
                                                                  ifelse(symptomatic,
                                                                         inf_ct_sympA_K_rand.sum/risk_ct_sympA_K_rand.sum,
                                                                         inf_ct_asympA_K_rand.sum/risk_ct_asympA_K_rand.sum)),
                                                           ifelse(adult.susp,
                                                                  ifelse(symptomatic,
                                                                         inf_ct_sympK_A_rand.sum/risk_ct_sympK_A_rand.sum,
                                                                         inf_ct_asympK_A_rand.sum/risk_ct_asympK_A_rand.sum),
                                                                  ifelse(symptomatic,
                                                                         inf_ct_sympK_K_rand.sum/risk_ct_sympK_K_rand.sum,
                                                                         inf_ct_asympK_K_rand.sum/risk_ct_asympK_K_rand.sum))),
                                                    ifelse(location == "staff.random",
                                                           ifelse(adult.source,
                                                                  ifelse(adult.susp,
                                                                         ifelse(symptomatic,
                                                                                inf_ct_sympA_A_staff.sum/risk_ct_sympA_A_staff.sum,
                                                                                inf_ct_asympA_A_staff.sum/risk_ct_asympA_A_staff.sum),
                                                                         ifelse(symptomatic,
                                                                                NA,
                                                                                NA)),
                                                                  ifelse(adult.susp,
                                                                         ifelse(symptomatic,
                                                                                NA,
                                                                                NA),
                                                                         ifelse(symptomatic,
                                                                                NA,
                                                                                NA))),
                                                           ifelse(location == "care",
                                                                  ifelse(adult.source,
                                                                         ifelse(adult.susp,
                                                                                ifelse(symptomatic,
                                                                                       inf_ct_sympA_A_care.sum/risk_ct_sympA_A_care.sum,
                                                                                       inf_ct_asympA_A_care.sum/risk_ct_asympA_A_care.sum),
                                                                                ifelse(symptomatic,
                                                                                       inf_ct_sympA_K_care.sum/risk_ct_sympA_K_care.sum,
                                                                                       inf_ct_asympA_K_care.sum/risk_ct_asympA_K_care.sum)),
                                                                         ifelse(adult.susp,
                                                                                ifelse(symptomatic,
                                                                                       inf_ct_sympK_A_care.sum/risk_ct_sympK_A_care.sum,
                                                                                       inf_ct_asympK_A_care.sum/risk_ct_asympK_A_care.sum),
                                                                                ifelse(symptomatic,
                                                                                       inf_ct_sympK_K_care.sum/risk_ct_sympK_K_care.sum,
                                                                                       inf_ct_asympK_K_care.sum/risk_ct_asympK_K_care.sum))),
                                                                  -99)))))),
         rel.diff = observed.sar/expected.sar) %>%
  relocate(observed.sar) %>%
  relocate(rel.diff)
                    
#Create table to compare observed parameters with input parameters SAR                    
other.param.compare <- expand.grid(group = output$group, parameter = c("Length of Infectiousness",
                                                                       "Length of Infectiousness at School (symptomatic, kid/teacher)", 
                                                                       "Length of Infectiousness at School (asymptomatic, kid/teacher)",
                                                                       "Length of Infectiousness at Care (symptomatic, family)", 
                                                                       "Length of Infectiousness at Care (asymptomatic, family)", 
                                                                       "Time from exposure to infectiousness", 
                                                                       "Time from exposure to symptoms", 
                                                                       "Number of students", 
                                                                       "Number of teachers", 
                                                                       "Number of non-classroom staff", 
                                                                       "Probability of Asymptomatic (adult)", 
                                                                       "Probability of Asymptomatic (kid)", 
                                                                       "Probability of Subclinical (adult)", 
                                                                       "Probability of Subclinical (kid)", 
                                                                       "Child Vaccination Rate", 
                                                                       "Teacher Vaccination Rate", 
                                                                       "Family Vaccination Rate", 
                                                                       "Community Incidence Rate (kid)", 
                                                                       "Community Incidence Rate (adult)",
                                                                       "PCR Sensitivity",
                                                                       "Rapid Test Sensitivity",
                                                                       "Regular Test Coverage",
                                                                       "Test Quarantine Coverage")) %>%
  relocate(parameter) %>%
  left_join(output, by = "group") %>%
  mutate(expected.param = ifelse(parameter == "Length of Infectiousness",
                            days_inf,
                            ifelse(parameter == "Length of Infectiousness at School (symptomatic, kid/teacher)",
                                   2*ifelse(test, test_sens*test_frac*(2/7)*0.5 + (1-test_frac*test_sens*(2/7)), 1),
                                   ifelse(parameter == "Length of Infectiousness at School (asymptomatic, kid/teacher)",
                                          days_inf*ifelse(test, test_sens*test_frac*(days_inf/7)*0.5 + (1-test_frac*test_sens*(days_inf/7)), 1),
                                          ifelse(parameter == "Time from exposure to infectiousness",
                                                 mean(sapply(rgamma(1000, shape = 5.8, scale=.95) - rnorm(1000, mean = 2, sd = 0.4), function(a){max(a,1)})),
                                                 ifelse(parameter == "Time from exposure to symptoms",
                                                        mean(rgamma(1000, shape = 5.8, scale=.95)),
                                                        ifelse(parameter == "Number of students",
                                                               ifelse(high_school, 1451, 638),
                                                               ifelse(parameter == "Number of teachers",
                                                                      ifelse(high_school, 4, 6)*n_class,
                                                                      ifelse(parameter == "Number of non-classroom staff",
                                                                             n_staff_obs.mean,
                                                                             ifelse(parameter == "Probability of Asymptomatic (adult)",
                                                                                    p_asymp_adult,
                                                                                    ifelse(parameter == "Probability of Asymptomatic (kid)",
                                                                                           p_asymp_child,
                                                                                           ifelse(parameter == "Probability of Subclinical (adult)",
                                                                                                  p_subclin_adult + p_asymp_adult,
                                                                                                  ifelse(parameter == "Probability of Subclinical (kid)",
                                                                                                         p_subclin_child + p_asymp_child,
                                                                                                         ifelse(parameter == "Child Vaccination Rate",
                                                                                                                child.vax,
                                                                                                                ifelse(parameter == "Teacher Vaccination Rate",
                                                                                                                       teacher_susp,
                                                                                                                       ifelse(parameter == "Family Vaccination Rate",
                                                                                                                              family_susp,
                                                                                                                              ifelse(parameter == "Community Incidence Rate (kid)",
                                                                                                                                     child_prob*((1 - child.vax)+child.vax*(1-vax_eff)),
                                                                                                                                     ifelse(parameter == "Community Incidence Rate (adult)",
                                                                                                                                            adult_prob*((1-family_susp)+family_susp*(1-vax_eff)),
                                                                                                                                            ifelse(parameter == "Length of Infectiousness at Care (symptomatic, family)",
                                                                                                                                                   mean(rnorm(1000, mean = 2, sd = 0.4)),
                                                                                                                                                   ifelse(parameter == "Length of Infectiousness at Care (asymptomatic, family)",
                                                                                                                                                          days_inf, -99)))))))))))))))))))) %>%
  mutate(expected.param = ifelse(parameter == "PCR Sensitivity",
                                 test_sens,
                                 ifelse(parameter == "Rapid Test Sensitivity",
                                        rapid_test_sens,
                                        ifelse(parameter == "Regular Test Coverage",
                                               test_frac,
                                               ifelse(parameter == "Test Quarantine Coverage",
                                                      1,
                                                      expected.param))))) %>%
  relocate(expected.param) %>%
  mutate(obs.param = ifelse(parameter == "Length of Infectiousness",
                            length.infectious_obs.mean,
                            ifelse(parameter == "Length of Infectiousness at School (symptomatic, kid/teacher)",
                                   length.infectious.school.symp.present_obs.mean,
                                   ifelse(parameter == "Length of Infectiousness at School (asymptomatic, kid/teacher)",
                                          length.infectious.school.asymp.present_obs.mean,
                                          ifelse(parameter == "Time from exposure to infectiousness",
                                                 length.incubation_obs.mean,
                                                 ifelse(parameter == "Time from exposure to symptoms",
                                                        length.symp.gap_obs.mean,
                                                        ifelse(parameter == "Number of students",
                                                               n_students_obs.mean,
                                                               ifelse(parameter == "Number of teachers",
                                                                      n_teachers_obs.mean,
                                                                      ifelse(parameter == "Number of non-classroom staff",
                                                                             n_staff_obs.mean,
                                                                             ifelse(parameter == "Probability of Asymptomatic (adult)",
                                                                                    p_asymp_adult_obs.mean,
                                                                                    ifelse(parameter == "Probability of Asymptomatic (kid)",
                                                                                           p_asymp_child_obs.mean,
                                                                                           ifelse(parameter == "Probability of Subclinical (adult)",
                                                                                                  p_subclin_adult_obs.mean,
                                                                                                  ifelse(parameter == "Probability of Subclinical (kid)",
                                                                                                         p_subclin_child_obs.mean,
                                                                                                         ifelse(parameter == "Child Vaccination Rate",
                                                                                                                child.vax.rate_obs.mean,
                                                                                                                ifelse(parameter == "Teacher Vaccination Rate",
                                                                                                                       teacher.vax.rate_obs.mean,
                                                                                                                       ifelse(parameter == "Family Vaccination Rate",
                                                                                                                              family.vax.rate_obs.mean,
                                                                                                                              ifelse(parameter == "Community Incidence Rate (kid)",
                                                                                                                                     child.prob_obs.mean,
                                                                                                                                     ifelse(parameter == "Community Incidence Rate (adult)",
                                                                                                                                            adult.prob_obs.mean,
                                                                                                                                            ifelse(parameter == "Length of Infectiousness at Care (symptomatic, family)",
                                                                                                                                                   length.infectious.school.symp.present_obs.mean,
                                                                                                                                                   ifelse(parameter == "Length of Infectiousness at Care (asymptomatic, family)",
                                                                                                                                                          length.infectious.school.asymp.present_obs.mean,-99)))))))))))))))))))) %>%
  mutate(obs.param = ifelse(parameter == "PCR Sensitivity",
                                   pcr_test_sens.obs/test_regular_frac.obs,
                                   ifelse(parameter == "Rapid Test Sensitivity",
                                          rapid_test_sens.obs/test_quarantine_frac.obs,
                                          ifelse(parameter == "Regular Test Coverage",
                                                 test_regular_frac.obs,
                                                 ifelse(parameter == "Test Quarantine Coverage",
                                                        test_quarantine_frac.obs,
                                                        obs.param))))) %>%
  relocate(obs.param) %>%
  mutate(rel.diff = obs.param/expected.param) %>%
  relocate(rel.diff)
